server:
  port: 8001

spring:
  application:
    name: springBoot
  jpa:
    properties:
      hibernate:
        default_schema: employee_management_system
      database: mysql
    hibernate:
      dialect: ${spring.jpa.properties.hibernate.dialect}
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.jdbc.lob.non_contextual_creation: true
        hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: arkar122181

format:
  date: dd-MM-yyyy
  date-time: dd-MM-yyyy:HH:mm:ss